---

- include: install.yml
  when: mailgun_install

- include: install.yml
  when: mailgun_setup

- name: Set root's email forward
  lineinfile:
    dest: /root/.forward
    create: yes
    line: "{{ root_forward }}"
  when:
    - root_forward is defined
