---

- include_tasks: install.yml
  when: mailgun_install

- include_tasks: setup.yml
  when: mailgun_setup

- name: Include Mailgun configuration in main.conf
  lineinfile:
    dest: /etc/postfix/main.cf
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
  with_items:
    - { regexp: "^relayhost", line: "relayhost = [{{ mailgun_smtp_host }}]:{{ mailgun_smtp_port }}" }
    - { regexp: "^smtp_tls_security_level", line: "smtp_tls_security_level = encrypt" }
    - { regexp: "^smtp_tls_note_starttls_offer", line: "smtp_tls_note_starttls_offer = yes" }
    - { regexp: '^smtp_use_tls', line: "smtp_use_tls = yes"}
    - { regexp: "^smtp_sasl_auth_enable", line: "smtp_sasl_auth_enable = yes" }
    - { regexp: "^smtp_sasl_security_options", line: "smtp_sasl_security_options = noanonymous" }
    - { regexp: "^smtp_sasl_password_maps", line: "smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd" }
  notify:
    - restart postfix

- name: Ensure Postfix will start if setup
  service:
    name: postfix
    state: "{% if mailgun_setup %}started{% else %}stopped{% endif %}"
    enabled: "{% if mailgun_setup %}yes{% else %}no{% endif %}"

- name: Set root's email forward
  lineinfile:
    dest: /root/.forward
    create: yes
    line: "{{ root_forward }}"
  when:
    - root_forward is defined
